---
language: php
install:
  - pip3 install gplaycli
  - composer install
before_script: sed -i -e "s/l.decode('utf-8')/l/"
    vendor/exodus-privacy/exodus-standalone/exodus_analyze.py
php: 7.1
dist: xenial
addons:
  apt:
    packages:
      - python3-lxml
      - python3-pyasn1
      - python3-cryptography
      - python3-future
      - python3-pip
      - python3-setuptools
      - dexdump
