---
language: php
install:
  - pip3 install gplaycli
  - composer install
php: 7.3
dist: xenial
addons:
  apt:
    packages:
      - python3-lxml
      - python3-pyasn1
      - python3-cryptography
      - python3-future
      - python3-pip
      - python3-setuptools
      - dexdump
