#!/usr/bin/env php
<?php
use ExodusFdroid\ScanCommand;
use Symfony\Component\Console\Application;

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    // Package is installed globally.
    require __DIR__.'/../../autoload.php';
}

$app = new Application('exodus-fdroid');
$scanCommand = new ScanCommand();
$app->add($scanCommand);
$app->setDefaultCommand($scanCommand->getName(), true);
if (isset($_SERVER['argv'])) {
    $app->run();
}
